# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RPC-Lite
version:      0.20
version_from: lib/RPC/Lite.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    IO::Select:                    0
    IO::Socket:                    0
    JSON:                          2.12 
    threads:                       0
    threads::shared:               0
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
